### ISSUE TITLE
FAQ Bot

### ISSUE THREAD

**Issue by spaetz** [maubot/plugin-wishlist#20]
As a special kind of support bot, it would be great if a maubot plugin could be told FAQ entries that can easily be triggered.

Example:

me: @bot learn matrix "Matrix is a cool chat system"
bot: learned entry 'matrix'

me: !FAQ matrix
@bot: "Matrix is a cool chat system"

me: @bot forget matrix
@bot: forgot entry 'matrix'

**Comment by ggogel** [comment]
Besides the learning, this can be done with the reactbot. I think for the learning you would want to have some kind of authorization, as otherwise everyone could execute the learning command.
https://github.com/maubot/reactbot

**Comment by williamkray** [comment]
you could use my [gifme plugin](https://github.com/williamkray/maubot-gifme), which is intended primarily to save gifs, but also functions as a way to save text as a quote from somebody. it returns the original text and attributes it to the person who said it. the only issue with it is that it doesn't save edits that have been made to the text, but that's something i'd eventually like to fix (PRs welcome!).

if you used it for that purpose, i would recommend using the following settings in the config:

```yaml
command_aliases:
    - faq
allow_fallback: false
fallback_threshold: 1
giphy_api_key: ''

## allow saving messages in plain-text to the database? security risk for encrypted rooms!
allow_non_files: true

## define a list of users who can save messages to the database?
restrict_users: true

allowed_users:
    - '@your:user.server'
```
